### PR TITLE
fix player track selection - offset MediaStream indexes to account for external tracks

### LINKED ISSUE #1729: Playback "randomly" fails and loops over and over
### Describe the bug

I can't reproduce it 100%, but one particular 4K HDR HEVC file seems to do it very often (though sometimes decide to directplay just fine, sometimes decide to transcode, but mostly not play at all). I've had it happen on other non-hdr files as well. Playback works reliably on an external player like VLC, but libVLC and Exo in the app have the same strange looping behaviour.

I've included a logcat, where it fails to play this file over and over. FFmpeg logs is from a transcode, so probably not that relevant as it should directplay.

### Logs

```shell
05-22 21:06:31.126 18522 18576 D jellyfin-apiclient: Web socket message received.
05-22 21:06:31.127 18522 18576 I jellyfin-apiclient: Received web socket message: UserDataChanged
05-22 21:06:31.265 18522 18522 D VideoManager: re-retrieved exoplayer track index 2
05-22 21:06:31.265 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:31.266 18522 18522 I PlaybackController: Play method: Direct
05-22 21:06:31.266 18522 18522 I PlaybackController: Turning off subs
05-22 21:06:31.266 18522 18522 D PlaybackController: Setting subtitle index to: -1
05-22 21:06:31.267 18522 18522 D PlaybackController: trying to switch audio stream from 2 to 3
05-22 21:06:31.267 18522 18522 D VideoManager: MediaStream track 0 type Subtitle label null codec subrip isExternal true
05-22 21:06:31.268 18522 18522 D VideoManager: MediaStream track 1 type Video label null codec hevc isExternal false
05-22 21:06:31.268 18522 18522 D VideoManager: MediaStream track 2 type Audio label null codec truehd isExternal false
05-22 21:06:31.268 18522 18522 D VideoManager: MediaStream track 3 type Audio label null codec aac isExternal false
05-22 21:06:31.268 18522 18522 D VideoManager: MediaStream track 4 type Subtitle label null codec subrip isExternal false
05-22 21:06:31.269 18522 18522 D VideoManager: MediaStream track 5 type Audio label null codec ac3 isExternal false
05-22 21:06:31.269 18522 18522 D VideoManager: track 1 group 1/1 trackType 2 label null mime video/hevc isSelected true isSupported true
05-22 21:06:31.269 18522 18522 D VideoManager: track 3 group 1/1 trackType 1 label null mime audio/mp4a-latm isSelected true isSupported true
05-22 21:06:31.270 18522 18522 D VideoManager: track 2 group 1/1 trackType 1 label null mime audio/true-hd isSelected false isSupported true
05-22 21:06:31.270 18522 18522 D VideoManager: track 5 group 1/1 trackType 1 label null mime audio/ac3 isSelected false isSupported true
05-22 21:06:31.270 18522 18522 D VideoManager: track 4 group 1/1 trackType 3 label null mime application/x-subrip isSelected false isSupported true
05-22 21:06:31.271 18522 18522 D PlaybackController: stop called at 2704550
05-22 21:06:31.271  3527  7570 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:31.273 18522 19695 D AudioTrack: getTimestamp_l(416): device stall time corrected using current time 5400407025908
05-22 21:06:31.277 18522 21166 I MediaCodec: [OMX.Nvidia.h265.decode] setting surface generation to 18966822
05-22 21:06:31.277 18522 21166 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
05-22 21:06:31.279  3411 21174 I SimpleSoftOMXComponent: state: 2, mState: 3 mTargetState: 3
05-22 21:06:31.279  3411 21174 I SimpleSoftOMXComponent: state: 1, mState: 2 mTargetState: 2
05-22 21:06:31.315  3239  3310 V hdcp up : tsec_version: 1
05-22 21:06:31.335  3527  7570 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:31.422 18522 18522 I jellyfin-apiclient: ReportPlaybackStopped: Item eea81288bee1100fe3ad860750c0071d, Ticks: 27045500000
05-22 21:06:31.422 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:31.423 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:31.425 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:31.480 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:31.481 18522 18522 I PlaybackController: VLC would direct stream
05-22 21:06:31.482 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:31.588 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:31.589 18522 18522 I PlaybackController: Internal player would direct stream
05-22 21:06:31.590 18522 18522 I PlaybackController: Explicit deinterlacing will NOT be used
05-22 21:06:31.590 18522 18522 I PlaybackController: User preferred player is: EXOPLAYER
05-22 21:06:31.591 18522 18522 I PlaybackController: Will use internal player
05-22 21:06:31.591 18522 18522 D PlaybackController: default audio index set to 2
05-22 21:06:31.593 18522 18522 D PlaybackController: default sub index set to -1 remote default -1
05-22 21:06:31.593 18522 18522 I PlaybackController: Playing back in native mode.
05-22 21:06:31.594 18522 18522 D VideoManager: Setting playback speed: 1.000000
05-22 21:06:31.599 18522 18522 I VideoManager: Video path set to: https://my.jellyfin.site/Videos/eea81288bee1100fe3ad860750c0071d/stream.mkv?api_key=<some-api-key>&DeviceId=632cca64f4ea714b0f588807c86d67e736a73145&MediaSourceId=eea81288bee1100fe3ad860750c0071d&Tag=651076d45881ff707bc98a15b9dccf56&Static=true
05-22 21:06:31.601 18522 18522 D VideoManager: Caught player timeline change - reason: PLAYLIST_CHANGED
05-22 21:06:31.601 18522 18522 D VideoManager: Tracks info changed
05-22 21:06:31.602 18522 18522 D VideoManager: Player is buffering
05-22 21:06:31.602 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing
05-22 21:06:31.603 18522 18522 I ReportingHelper: Playback of Rogue One: A Star Wars Story started.
05-22 21:06:31.603 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:31.606 18522 18522 D VideoManager: Caught player timeline change - reason: SOURCE_UPDATE
05-22 21:06:31.893 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing
05-22 21:06:31.935 18522 19695 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [sif, SHIELD Android TV, NVIDIA, 30]
05-22 21:06:31.935 18522 19695 I chatty  : uid=10107(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
05-22 21:06:31.938 18522 19695 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [sif, SHIELD Android TV, NVIDIA, 30]
05-22 21:06:31.939 18522 18522 D VideoManager: Caught player timeline change - reason: SOURCE_UPDATE
05-22 21:06:31.940 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.940 18522 18522 D VideoManager: Tracks info changed
05-22 21:06:31.942 18522 21183 I OMXClient: IOmx service obtained
05-22 21:06:31.942  3411 16281 I OMXMaster: makeComponentInstance(OMX.Nvidia.h265.decode) in android.hardwar process
05-22 21:06:31.946 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.948 18522 19695 I chatty  : uid=10107(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
05-22 21:06:31.949 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.950 18522 21182 I MediaCodec: [OMX.Nvidia.h265.decode] setting surface generation to 18966823
05-22 21:06:31.955 18522 21183 I ACodec  : Enable timestamp filtering for Video Decoder
05-22 21:06:31.956 18522 21183 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:31.956 18522 21183 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:31.961  3407  3407 W ResourceManagerService: Ignoring request to add new resource entry with value <= 0
05-22 21:06:31.963 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.965 18522 21189 I OMXClient: IOmx service obtained
05-22 21:06:31.965  3411 16281 I OMXMaster: makeComponentInstance(OMX.google.aac.decoder) in android.hardwar process
05-22 21:06:31.968 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.970 18522 19695 I chatty  : uid=10107(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
05-22 21:06:31.971 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:31.972 18522 21189 I ACodec  : codec does not support config priority (err -2147483648)
05-22 21:06:31.972 18522 21189 I ACodec  : codec does not support config operating rate (err -2147483648)
05-22 21:06:31.973  3411 16281 D SoftAAC2: get OMX_IndexParamAudioAndroidAacDrcPresentation
05-22 21:06:31.973  3411 21190 I SimpleSoftOMXComponent: state: 2, mState: 1 mTargetState: 1
05-22 21:06:31.976  3411 21190 I SimpleSoftOMXComponent: state: 3, mState: 2 mTargetState: 2
05-22 21:06:32.092  3411 21190 I SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
05-22 21:06:32.093  3411 16281 D SoftAAC2: get OMX_IndexParamAudioAndroidAacDrcPresentation
05-22 21:06:32.102 18522 21183 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:32.102 18522 21183 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:32.109  3259  7769 I APM_AudioPolicyManager: getOutput() stream 3 selected devices {type:0x400,@:}, output 13
05-22 21:06:32.109  3259  7769 I chatty  : uid=1041(audioserver) Binder:3259_7 identical 1 line
05-22 21:06:32.109  3259  7769 I APM_AudioPolicyManager: getOutput() stream 3 selected devices {type:0x400,@:}, output 13
05-22 21:06:32.111  3259  3460 I APM_AudioPolicyManager: getOutputForAttrInt() device {type:0x400,@:}, sampling rate 48000, format 0x1, channel mask 0x3, flags 0x8 stream AUDIO_STREAM_MUSIC
05-22 21:06:32.111  3212  3243 I nvaudio_hw: prop_get:hw_dev->is_native_sample_rate:0
05-22 21:06:32.113  3259  3460 I APM_AudioPolicyManager: getOutputForAttrInt returns output 13 selectedDeviceId 16
05-22 21:06:32.114  3259  3460 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000008) and output flags (00000006)
05-22 21:06:32.114  3259  3460 D AudioFlinger: Client defaulted notificationFrames to 6000 for frameCount 12000
05-22 21:06:32.115  3259  3460 D AF::TrackHandle: OpPlayAudio: track:449 usage:1 not muted
05-22 21:06:32.124 18522 21183 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:32.124 18522 21183 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:32.382 18522 18576 V WebSocketImpl: process(573): (ÔøΩ~9{"MessageType":"UserDataChanged","MessageId":"599b156c2e0f4969afc334c512f57e5f","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":463,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:32.0048087Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}})
05-22 21:06:32.383 18522 18576 V Draft_6455: afterDecoding(569): {"MessageType":"UserDataChanged","MessageId":"599b156c2e0f4969afc334c512f57e5f","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":463,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:32.0048087Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}}
05-22 21:06:32.383 18522 18576 V WebSocketImpl: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:569], payload:{"MessageType":"UserDataChanged","MessageId":"599b156c2e0f4969afc334c512f57e5f","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":463,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:32.0048087Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}}}
05-22 21:06:32.383 18522 18576 D jellyfin-apiclient: Web socket message received.
05-22 21:06:32.383 18522 18576 I jellyfin-apiclient: Received web socket message: UserDataChanged
05-22 21:06:32.488  3527  4748 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:32.488 18522 18522 D VideoManager: re-retrieved exoplayer track index 2
05-22 21:06:32.488 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:32.488 18522 18522 I PlaybackController: Play method: Direct
05-22 21:06:32.489 18522 18522 I PlaybackController: Turning off subs
05-22 21:06:32.489 18522 18522 D PlaybackController: Setting subtitle index to: -1
05-22 21:06:32.490 18522 18522 D PlaybackController: trying to switch audio stream from 2 to 3
05-22 21:06:32.490 18522 18522 D VideoManager: MediaStream track 0 type Subtitle label null codec subrip isExternal true
05-22 21:06:32.490 18522 18522 D VideoManager: MediaStream track 1 type Video label null codec hevc isExternal false
05-22 21:06:32.491 18522 18522 D VideoManager: MediaStream track 2 type Audio label null codec truehd isExternal false
05-22 21:06:32.491 18522 18522 D VideoManager: MediaStream track 3 type Audio label null codec aac isExternal false
05-22 21:06:32.491 18522 18522 D VideoManager: MediaStream track 4 type Subtitle label null codec subrip isExternal false
05-22 21:06:32.491 18522 18522 D VideoManager: MediaStream track 5 type Audio label null codec ac3 isExternal false
05-22 21:06:32.492 18522 18522 D VideoManager: track 1 group 1/1 trackType 2 label null mime video/hevc isSelected true isSupported true
05-22 21:06:32.492 18522 18522 D VideoManager: track 3 group 1/1 trackType 1 label null mime audio/mp4a-latm isSelected true isSupported true
05-22 21:06:32.492 18522 18522 D VideoManager: track 2 group 1/1 trackType 1 label null mime audio/true-hd isSelected false isSupported true
05-22 21:06:32.493 18522 18522 D VideoManager: track 5 group 1/1 trackType 1 label null mime audio/ac3 isSelected false isSupported true
05-22 21:06:32.493 18522 18522 D VideoManager: track 4 group 1/1 trackType 3 label null mime application/x-subrip isSelected false isSupported true
05-22 21:06:32.493 18522 18522 D PlaybackController: stop called at 2704550
05-22 21:06:32.498 18522 21182 I MediaCodec: [OMX.Nvidia.h265.decode] setting surface generation to 18966824
05-22 21:06:32.499 18522 21182 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
05-22 21:06:32.500  3411 21190 I SimpleSoftOMXComponent: state: 2, mState: 3 mTargetState: 3
05-22 21:06:32.501  3411 21190 I SimpleSoftOMXComponent: state: 1, mState: 2 mTargetState: 2
05-22 21:06:32.551  3527  7570 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:32.644 18522 18522 I jellyfin-apiclient: ReportPlaybackStopped: Item eea81288bee1100fe3ad860750c0071d, Ticks: 27045500000
05-22 21:06:32.644 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:32.645 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:32.647 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:32.703 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:32.704 18522 18522 I PlaybackController: VLC would direct stream
05-22 21:06:32.705 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:32.789 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:32.791 18522 18522 I PlaybackController: Internal player would direct stream
05-22 21:06:32.792 18522 18522 I PlaybackController: Explicit deinterlacing will NOT be used
05-22 21:06:32.792 18522 18522 I PlaybackController: User preferred player is: EXOPLAYER
05-22 21:06:32.792 18522 18522 I PlaybackController: Will use internal player
05-22 21:06:32.793 18522 18522 D PlaybackController: default audio index set to 2
05-22 21:06:32.795 18522 18522 D PlaybackController: default sub index set to -1 remote default -1
05-22 21:06:32.795 18522 18522 I PlaybackController: Playing back in native mode.
05-22 21:06:32.796 18522 18522 D VideoManager: Setting playback speed: 1.000000
05-22 21:06:32.802 18522 18522 I VideoManager: Video path set to: https://my.jellyfin.site/Videos/eea81288bee1100fe3ad860750c0071d/stream.mkv?api_key=<some-api-key>&DeviceId=632cca64f4ea714b0f588807c86d67e736a73145&MediaSourceId=eea81288bee1100fe3ad860750c0071d&Tag=651076d45881ff707bc98a15b9dccf56&Static=true
05-22 21:06:32.803 18522 18522 D VideoManager: Caught player timeline change - reason: PLAYLIST_CHANGED
05-22 21:06:32.803 18522 18522 D VideoManager: Tracks info changed
05-22 21:06:32.804 18522 18522 D VideoManager: Player is buffering
05-22 21:06:32.805 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing
05-22 21:06:32.805 18522 18522 I ReportingHelper: Playback of Rogue One: A Star Wars Story started.
05-22 21:06:32.805 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:32.808 18522 18522 D VideoManager: Caught player timeline change - reason: SOURCE_UPDATE
05-22 21:06:33.014  3527  3607 D WindowManager: handleComboKeys keyCode: 4, keyAction: 0
05-22 21:06:33.038 18522 19695 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [sif, SHIELD Android TV, NVIDIA, 30]
05-22 21:06:33.039 18522 19695 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [sif, SHIELD Android TV, NVIDIA, 30]
05-22 21:06:33.041 18522 18522 D VideoManager: Caught player timeline change - reason: SOURCE_UPDATE
05-22 21:06:33.048 18522 19695 D MediaCodecInfo: NoSupport [codec.profileLevel, hvc1.2.4.H153.90, video/hevc] [OMX.google.hevc.decoder, video/hevc] [sif, SHIELD Android TV, NVIDIA, 30]
05-22 21:06:33.050 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.053 18522 21197 I OMXClient: IOmx service obtained
05-22 21:06:33.053  3411  3475 I OMXMaster: makeComponentInstance(OMX.Nvidia.h265.decode) in android.hardwar process
05-22 21:06:33.055 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.057 18522 18522 D VideoManager: Tracks info changed
05-22 21:06:33.058 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.060 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.061 18522 21196 I MediaCodec: [OMX.Nvidia.h265.decode] setting surface generation to 18966825
05-22 21:06:33.066 18522 21197 I ACodec  : Enable timestamp filtering for Video Decoder
05-22 21:06:33.067 18522 21197 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:33.067 18522 21197 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:33.071  3407  3407 W ResourceManagerService: Ignoring request to add new resource entry with value <= 0
05-22 21:06:33.077 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.079 18522 21203 I OMXClient: IOmx service obtained
05-22 21:06:33.079  3411  3475 I OMXMaster: makeComponentInstance(OMX.google.aac.decoder) in android.hardwar process
05-22 21:06:33.082 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.083 18522 19695 I chatty  : uid=10107(org.jellyfin.androidtv) ExoPlayer:Playb identical 1 line
05-22 21:06:33.085 18522 19695 I android_os_HwBinder: HwBinder: Starting thread pool for getting: vendor.nvidia.hardware.cpl.service_common@1.0::INvCplHalCommonService/default
05-22 21:06:33.086 18522 21203 I ACodec  : codec does not support config priority (err -2147483648)
05-22 21:06:33.086 18522 21203 I ACodec  : codec does not support config operating rate (err -2147483648)
05-22 21:06:33.087  3411  3475 D SoftAAC2: get OMX_IndexParamAudioAndroidAacDrcPresentation
05-22 21:06:33.087  3411 21204 I SimpleSoftOMXComponent: state: 2, mState: 1 mTargetState: 1
05-22 21:06:33.089 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing
05-22 21:06:33.093  3411 21204 I SimpleSoftOMXComponent: state: 3, mState: 2 mTargetState: 2
05-22 21:06:33.095  3411 21204 I SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
05-22 21:06:33.095  3411  7680 D SoftAAC2: get OMX_IndexParamAudioAndroidAacDrcPresentation
05-22 21:06:33.103  3259 16909 I APM_AudioPolicyManager: getOutput() stream 3 selected devices {type:0x400,@:}, output 13
05-22 21:06:33.103  3259 16909 I APM_AudioPolicyManager: getOutput() stream 3 selected devices {type:0x400,@:}, output 13
05-22 21:06:33.104  3259  3259 I APM_AudioPolicyManager: getOutput() stream 3 selected devices {type:0x400,@:}, output 13
05-22 21:06:33.107  3259 16909 I APM_AudioPolicyManager: getOutputForAttrInt() device {type:0x400,@:}, sampling rate 48000, format 0x1, channel mask 0x3, flags 0x8 stream AUDIO_STREAM_MUSIC
05-22 21:06:33.107  3212  3212 I nvaudio_hw: prop_get:hw_dev->is_native_sample_rate:0
05-22 21:06:33.108  3259 16909 I APM_AudioPolicyManager: getOutputForAttrInt returns output 13 selectedDeviceId 16
05-22 21:06:33.108  3259 16909 W AudioFlinger: createTrack_l(): mismatch between requested flags (00000008) and output flags (00000006)
05-22 21:06:33.108  3259 16909 D AudioFlinger: Client defaulted notificationFrames to 6000 for frameCount 12000
05-22 21:06:33.110  3259 16909 D AF::TrackHandle: OpPlayAudio: track:450 usage:1 not muted
05-22 21:06:33.113 18522 21197 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:33.113 18522 21197 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:33.136 18522 21197 I ACodec  : Get OMX_IndexConfigScale: 0x10000/0x10000
05-22 21:06:33.136 18522 21197 I ACodec  : Scaled Width is 3840, height is 1608
05-22 21:06:33.239  3527  3607 D WindowManager: handleComboKeys keyCode: 4, keyAction: 1
05-22 21:06:33.447  3527  4748 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:33.450 18522 19695 D AudioTrack: getTimestamp_l(418): device stall time corrected using current time 5402584557886
05-22 21:06:33.456 18522 18522 D VideoManager: re-retrieved exoplayer track index 2
05-22 21:06:33.456 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:33.457 18522 18522 I PlaybackController: Play method: Direct
05-22 21:06:33.457 18522 18522 I PlaybackController: Turning off subs
05-22 21:06:33.458 18522 18522 D PlaybackController: Setting subtitle index to: -1
05-22 21:06:33.458 18522 18522 D PlaybackController: trying to switch audio stream from 2 to 3
05-22 21:06:33.458 18522 18522 D VideoManager: MediaStream track 0 type Subtitle label null codec subrip isExternal true
05-22 21:06:33.459 18522 18522 D VideoManager: MediaStream track 1 type Video label null codec hevc isExternal false
05-22 21:06:33.459 18522 18522 D VideoManager: MediaStream track 2 type Audio label null codec truehd isExternal false
05-22 21:06:33.459 18522 18522 D VideoManager: MediaStream track 3 type Audio label null codec aac isExternal false
05-22 21:06:33.459 18522 18522 D VideoManager: MediaStream track 4 type Subtitle label null codec subrip isExternal false
05-22 21:06:33.459 18522 18522 D VideoManager: MediaStream track 5 type Audio label null codec ac3 isExternal false
05-22 21:06:33.459 18522 18522 D VideoManager: track 1 group 1/1 trackType 2 label null mime video/hevc isSelected true isSupported true
05-22 21:06:33.460 18522 18522 D VideoManager: track 3 group 1/1 trackType 1 label null mime audio/mp4a-latm isSelected true isSupported true
05-22 21:06:33.460 18522 18522 D VideoManager: track 2 group 1/1 trackType 1 label null mime audio/true-hd isSelected false isSupported true
05-22 21:06:33.460 18522 18522 D VideoManager: track 5 group 1/1 trackType 1 label null mime audio/ac3 isSelected false isSupported true
05-22 21:06:33.460 18522 18522 D VideoManager: track 4 group 1/1 trackType 3 label null mime application/x-subrip isSelected false isSupported true
05-22 21:06:33.460 18522 18522 D PlaybackController: stop called at 2704550
05-22 21:06:33.465 18522 21196 I MediaCodec: [OMX.Nvidia.h265.decode] setting surface generation to 18966826
05-22 21:06:33.466 18522 21196 E Surface : freeAllBuffers: 12 buffers were freed while being dequeued!
05-22 21:06:33.467  3411 21204 I SimpleSoftOMXComponent: state: 2, mState: 3 mTargetState: 3
05-22 21:06:33.468  3411 21204 I SimpleSoftOMXComponent: state: 1, mState: 2 mTargetState: 2
05-22 21:06:33.529  3527  4748 I system_server: oneway function results will be dropped but finished with status OK and parcel size 4
05-22 21:06:33.588  3527  3607 D WindowManager: handleComboKeys keyCode: 4, keyAction: 0
05-22 21:06:33.595 18522 18576 V WebSocketImpl: process(573): (ÔøΩ~9{"MessageType":"UserDataChanged","MessageId":"f2a3e9aece8d442e8ca9a3c80fbd9edb","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":464,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:33.2115187Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}})
05-22 21:06:33.595 18522 18576 V Draft_6455: afterDecoding(569): {"MessageType":"UserDataChanged","MessageId":"f2a3e9aece8d442e8ca9a3c80fbd9edb","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":464,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:33.2115187Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}}
05-22 21:06:33.596 18522 18576 V WebSocketImpl: matched frame: Framedata{ optcode:TEXT, fin:true, rsv1:false, rsv2:false, rsv3:false, payloadlength:[pos:0, len:569], payload:{"MessageType":"UserDataChanged","MessageId":"f2a3e9aece8d442e8ca9a3c80fbd9edb","Data":{"UserId":"11e69615e9fa400ebe8e0e5b638b314c","UserDataList":[{"PlayedPercentage":33.64779125777533,"PlaybackPositionTicks":27045500000,"PlayCount":464,"IsFavorite":false,"LastPlayedDate":"2022-05-22T19:06:33.2115187Z","Played":false,"Key":"330459","ItemId":"eea81288bee1100fe3ad860750c0071d"},{"UnplayedItemCount":1,"PlaybackPositionTicks":0,"PlayCount":0,"IsFavorite":false,"Played":false,"Key":"cefb8207-cb20-00a4-5b81-9fbf74929484","ItemId":"cefb8207cb2000a45b819fbf74929484"}]}}}
05-22 21:06:33.596 18522 18576 D jellyfin-apiclient: Web socket message received.
05-22 21:06:33.596 18522 18576 I jellyfin-apiclient: Received web socket message: UserDataChanged
05-22 21:06:33.611 18522 18522 I jellyfin-apiclient: ReportPlaybackStopped: Item eea81288bee1100fe3ad860750c0071d, Ticks: 27045500000
05-22 21:06:33.611 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:33.612 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:33.616 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Progress
05-22 21:06:33.763  3527  3607 D WindowManager: handleComboKeys keyCode: 4, keyAction: 1
05-22 21:06:33.773 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:33.774 18522 18522 I PlaybackController: VLC would direct stream
05-22 21:06:33.775 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:33.791 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Sessions/Playing/Stopped
05-22 21:06:33.940 18522 18522 I jellyfin-apiclient: Response received from: https://my.jellyfin.site/Items/eea81288bee1100fe3ad860750c0071d/PlaybackInfo?format=json
05-22 21:06:33.942 18522 18522 I PlaybackController: Internal player would direct stream
05-22 21:06:33.943 18522 18522 I PlaybackController: Explicit deinterlacing will NOT be used
05-22 21:06:33.944 18522 18522 I PlaybackController: User preferred player is: EXOPLAYER
05-22 21:06:33.944 18522 18522 I PlaybackController: Will use internal player
05-22 21:06:33.944 18522 18522 D PlaybackController: default audio index set to 2
05-22 21:06:33.945 18522 18522 D PlaybackController: default sub index set to -1 remote default -1
05-22 21:06:33.946 18522 18522 I PlaybackController: Playing back in native mode.
05-22 21:06:33.946 18522 18522 D VideoManager: Setting playback speed: 1.000000
05-22 21:06:33.951 18522 18522 I VideoManager: Video path set to: https://my.jellyfin.site/Videos/eea81288bee1100fe3ad860750c0071d/stream.mkv?api_key=<some-api-key>&DeviceId=632cca64f4ea714b0f588807c86d67e736a73145&MediaSourceId=eea81288bee1100fe3ad860750c0071d&Tag=651076d45881ff707bc98a15b9dccf56&Static=true
05-22 21:06:33.953 18522 18522 D VideoManager: Caught player timeline change - reason: PLAYLIST_CHANGED
05-22 21:06:33.953 18522 18522 D VideoManager: Tracks info changed
05-22 21:06:33.954 18522 18522 D VideoManager: Player is buffering
05-22 21:06:33.954 18522 18522 D jellyfin-apiclient: Adding request to queue: https://my.jellyfin.site/Sessions/Playing
```

### FFmpeg logs

```shell
/videos/eea81288-bee1-100f-e3ad-860750c0071d/hls1/main/900.ts

{"Protocol":0,"Id":"eea81288bee1100fe3ad860750c0071d","Path":"/media/Movies-HQ/Rogue.One.A.Star.Wars.Story_2016/Rogue.One.A.Star.Wars.Story.2016.2160p.UHD.BluRay.TrueHD.7.1.HDR.x265-CtrlHD/rogue.one.a.star.wars.story.2016.[tmdbid-330459].mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":42442072064,"Name":"rogue.one.a.star.wars.story.2016.[tmdbid-330459]","IsRemote":false,"ETag":"651076d45881ff707bc98a15b9dccf56","RunTimeTicks":80378232832,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"subrip","CodecTag":null,"Language":"swe","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Swe - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/media/Movies-HQ/Rogue.One.A.Star.Wars.Story_2016/Rogue.One.A.Star.Wars.Story.2016.2160p.UHD.BluRay.TrueHD.7.1.HDR.x265-CtrlHD/rogue.one.a.star.wars.story.2016.[tmdbid-330459].sv.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"HDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"4K HEVC HDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":42242357,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":1608,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"2.40:1","Index":1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":153,"IsAnamorphic":null},{"Codec":"truehd","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Eng - TRUEHD - 7.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"7.1","BitRate":4211168,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":8,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"aac","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Eng - AAC - Stereo - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":640000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Eng - Default - SUBRIP","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":4,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"ac3","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"Eng - Dolby Digital - 5.1","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":640000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":5,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":47733525,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:45:00.000 -init_hw_device vaapi=va:,driver=iHD -filter_hw_device va -autorotate 0 -i file:"/media/Movies-HQ/Rogue.One.A.Star.Wars.Story_2016/Rogue.One.A.Star.Wars.Story.2016.2160p.UHD.BluRay.TrueHD.7.1.HDR.x265-CtrlHD/rogue.one.a.star.wars.story.2016.[tmdbid-330459].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 h264_vaapi -rc_mode VBR -b:v 70403928 -maxrate 70403928 -bufsize 140807856 -profile:v:0 high -force_key_frames:0 "expr:gte(t,2700+n_forced*3)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(3840\,1608*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(3840/a\,1608))/2)*2,format=nv12,hwupload_vaapi" -codec:a:0 aac -ac 2 -ab 384000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 900 -hls_segment_filename "/archive-temp/transcode/jellyfin/6ed28ab842f90b690ab2cc1ed145cab6%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/archive-temp/transcode/jellyfin/6ed28ab842f90b690ab2cc1ed145cab6.m3u8"
```

### Media info of the file

```shell
ffprobe version N-58441-g8c1b65feb6-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      57.  4.101 / 57.  4.101
  libavcodec     59.  6.100 / 59.  6.100
  libavformat    59.  4.102 / 59.  4.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8.  6.100 /  8.  6.100
  libswscale      6.  0.100 /  6.  0.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, matroska,webm, from '/mnt/archive/Movies-HQ/Rogue.One.A.Star.Wars.Story_2016/Rogue.One.A.Star.Wars.Story.2016.2160p.UHD.BluRay.TrueHD.7.1.HDR.x265-CtrlHD/rogue.one.a.star.wars.story.2016.[tmdbid-330459].mkv':
  Metadata:
    ENCODER         : Lavf58.45.100
  Duration: 02:13:57.82, start: 0.000000, bitrate: 42242 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 154.529000
      Metadata:
        title           : Chapter 01
    Chapter #0:1: start 154.529000, end 466.341000
      Metadata:
        title           : Chapter 02
    Chapter #0:2: start 466.341000, end 522.689000
      Metadata:
        title           : Chapter 03
    Chapter #0:3: start 522.689000, end 664.497000
      Metadata:
        title           : Chapter 04
    Chapter #0:4: start 664.497000, end 741.074000
      Metadata:
        title           : Chapter 05
    Chapter #0:5: start 741.074000, end 821.028000
      Metadata:
        title           : Chapter 06
    Chapter #0:6: start 821.028000, end 1039.789000
      Metadata:
        title           : Chapter 07
    Chapter #0:7: start 1039.789000, end 1209.416000
      Metadata:
        title           : Chapter 08
    Chapter #0:8: start 1209.416000, end 1314.646000
      Metadata:
        title           : Chapter 09
    Chapter #0:9: start 1314.646000, end 1426.967000
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 1426.967000, end 1471.261000
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 1471.261000, end 1613.320000
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 1613.320000, end 1666.498000
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 1666.498000, end 1837.168000
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 1837.168000, end 2033.281000
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 2033.281000, end 2231.145000
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 2231.145000, end 2549.964000
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 2549.964000, end 2836.000000
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 2836.000000, end 3064.019000
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 3064.019000, end 3143.599000
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 3143.599000, end 3353.141000
      Metadata:
        title           : Chapter 21
    Chapter #0:21: start 3353.141000, end 3588.126000
      Metadata:
        title           : Chapter 22
    Chapter #0:22: start 3588.126000, end 3727.682000
      Metadata:
        title           : Chapter 23
    Chapter #0:23: start 3727.682000, end 3925.380000
      Metadata:
        title           : Chapter 24
    Chapter #0:24: start 3925.380000, end 4223.970000
      Metadata:
        title           : Chapter 25
    Chapter #0:25: start 4223.970000, end 4369.407000
      Metadata:
        title           : Chapter 26
    Chapter #0:26: start 4369.407000, end 4588.334000
      Metadata:
        title           : Chapter 27
    Chapter #0:27: start 4588.334000, end 4744.198000
      Metadata:
        title           : Chapter 28
    Chapter #0:28: start 4744.198000, end 4915.035000
      Metadata:
        title           : Chapter 29
    Chapter #0:29: start 4915.035000, end 5005.542000
      Metadata:
        title           : Chapter 30
    Chapter #0:30: start 5005.542000, end 5158.862000
      Metadata:
        title           : Chapter 31
    Chapter #0:31: start 5158.862000, end 5254.833000
      Metadata:
        title           : Chapter 32
    Chapter #0:32: start 5254.833000, end 5397.183000
      Metadata:
        title           : Chapter 33
    Chapter #0:33: start 5397.183000, end 5513.716000
      Metadata:
        title           : Chapter 34
    Chapter #0:34: start 5513.716000, end 5658.611000
      Metadata:
        title           : Chapter 35
    Chapter #0:35: start 5658.611000, end 5767.386000
      Metadata:
        title           : Chapter 36
    Chapter #0:36: start 5767.386000, end 5868.112000
      Metadata:
        title           : Chapter 37
    Chapter #0:37: start 5868.112000, end 6027.480000
      Metadata:
        title           : Chapter 38
    Chapter #0:38: start 6027.480000, end 6163.949000
      Metadata:
        title           : Chapter 39
    Chapter #0:39: start 6163.949000, end 6326.653000
      Metadata:
        title           : Chapter 40
    Chapter #0:40: start 6326.653000, end 6474.885000
      Metadata:
        title           : Chapter 41
    Chapter #0:41: start 6474.885000, end 6631.291000
      Metadata:
        title           : Chapter 42
    Chapter #0:42: start 6631.291000, end 6808.760000
      Metadata:
        title           : Chapter 43
    Chapter #0:43: start 6808.760000, end 6946.147000
      Metadata:
        title           : Chapter 44
    Chapter #0:44: start 6946.147000, end 7163.323000
      Metadata:
        title           : Chapter 45
    Chapter #0:45: start 7163.323000, end 7271.222000
      Metadata:
        title           : Chapter 46
    Chapter #0:46: start 7271.222000, end 7395.471000
      Metadata:
        title           : Chapter 47
    Chapter #0:47: start 7395.471000, end 7541.993000
      Metadata:
        title           : Chapter 48
    Chapter #0:48: start 7541.993000, end 8037.792000
      Metadata:
        title           : Chapter 49
  Stream #0:0(eng): Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1608, SAR 1:1 DAR 160:67, 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 37189941
      DURATION-eng    : 02:13:57.738000000
      NUMBER_OF_FRAMES-eng: 192713
      NUMBER_OF_BYTES-eng: 37365375627
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 19:47:05
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:13:57.758000000
  Stream #0:1(eng): Audio: truehd, 48000 Hz, 7.1, s32 (24 bit)
    Metadata:
      BPS-eng         : 4211168
      DURATION-eng    : 02:13:57.755000000
      NUMBER_OF_FRAMES-eng: 9645306
      NUMBER_OF_BYTES-eng: 4231042244
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 19:47:05
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:13:57.776000000
  Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      BPS-eng         : 640000
      DURATION-eng    : 02:13:57.792000000
      NUMBER_OF_FRAMES-eng: 251181
      NUMBER_OF_BYTES-eng: 643023360
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 19:47:05
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      ENCODER         : Lavc58.91.100 aac
      DURATION        : 02:13:57.823000000
  Stream #0:3(eng): Subtitle: subrip (default)
    Metadata:
      BPS-eng         : 47
      DURATION-eng    : 02:04:04.729000000
      NUMBER_OF_FRAMES-eng: 1563
      NUMBER_OF_BYTES-eng: 44611
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 19:47:05
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:05:35.174000000
  Stream #0:4(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      BPS-eng         : 640000
      DURATION-eng    : 02:13:57.792000000
      NUMBER_OF_FRAMES-eng: 251181
      NUMBER_OF_BYTES-eng: 643023360
      _STATISTICS_WRITING_APP-eng: mkvmerge v44.0.0 ('Domino') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-03 19:47:05
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      DURATION        : 02:13:57.813000000
```

### Application version

0.13.5

### Device information

Shield TV

### Android version

11

### Jellyfin server version

10.8.0 beta3

### PR DESCRIPTION
**Pull request by mueslimak3r**
**Changes**
* Added a `VideoManager` method to offset stream indexes for player track index <- -> MediaStream list index mapping. This accounts for external streams being at the beginning of the list. When mapping a MediaStream index to a player index, the index is decremented by 1 for every external track found prior to the embedded tracks in the list. It's incremented by 1 going player -> MediaStream.

* rearranged `getAudioStreamIndex()` so that, similar to how we keep track of which subtitle index is currently in use, `mCurrentOptions.AudioStreamIndex` is used to query the current index after it's set. This avoids the potentially expensive calls to the player APIs and looping through all the tracks every time we want to get the index.

* removed `exoplayerAudioIndex` from `VideoManager`. This was used to cache the current index. Now `mCurrentOptions.AudioStreamIndex` is used.

**Issues**
* With 10.8-beta3, and in some situations prior, the mapping of MediaStream (server side) track IDs/indexes <- -> libVLC/Exoplayer track IDs/indexes would be incorrect due to external tracks being in the MediaStream tracks list.

  The players (libVLC, Exoplayer) don't know that external tracks exist. So when the MediaStream tracks list contains external tracks prior to embedded tracks `eg: [external-track, external-track, embedded-track, embedded-track, ...]`, the indexes don't match up.

  Related server PR that standardized stream arrangement:
  https://github.com/jellyfin/jellyfin/pull/7529

* Fixes #1729

**Testing**
* Direct play video that has external subtitle tracks using exoplayer or libVLC
* Make sure the subtitle tracks can be selected without issues
* Make sure starting/resuming a video with external subtitles works without issues

**Notes**
* needs testing with 10.7.7
* if there's a less messy way to do this plz send help

### CODE REVIEW

**Comment by Gylesie** [comment]
Works nicely with the 10.8-beta3. Well done! It fixed my infinite loop, preventing some media from playing. Thanks!

**Comment by mueslimak3r** [comment]
tested both exoplayer and libVLC with a 10.7.7 server and I didn't notice any issues

File: app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java [hunk 1]
```diff
@@ -437,37 +432,43 @@ public void disableSubs() {
...
-            }
+        int vlcIndex = offsetStreamIndex(index, false, allStreams);
+
+        if (vlcIndex < 0)
+            return false;
 
-            Timber.i("Setting Vlc sub to %s", vlcSub.name);
-            return mVlcPlayer.setSpuTrack(vlcSub.id);
+        org.videolan.libvlc.MediaPlayer.TrackDescription vlcSub = null;
+        for (org.videolan.libvlc.MediaPlayer.TrackDescription subTrack: mVlcPlayer.getSpuTracks()) {
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java:458]: Why use full package names instead of importing MediaPlayer here?

Comment (mueslimak3r) [reply app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java:458]: That's a copy & paste from reordering the old code 😅. I'll change it to an import

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by agalera** [comment]
using server 10.8.0 and client 0.13.6 the audio selection works with libvlc but in exoplayer it always plays the first audio track

**Comment by mueslimak3r** [comment]
> using server 10.8.0 and client 0.13.6 the audio selection works with libvlc but in exoplayer it always plays the first audio track

I'll do some testing and see if I can reproduce this. Can you take a screenshot of the media info in the web client?
Just the part where it shows all the video, audio, embedded subs, and external subs (if present)

**Comment by mueslimak3r** [comment]
Also, which version is your server? 10.7.7, or if 10.8 is it the stable version or one of the alphas/betas?

**Comment by agalera** [comment]
Hello @mueslimak3r I have tried 10.8.0 (stable) and the latest unstable version, and I get the same result.

this video has 4 audios and only when I choose the last one 'English DD2.0 @ 256 kbps - Eng - Dolby Digital - Stereo' (Stream #0:4) it is heard in English. It happens to me in all the videos, if it has only 2 audios, the first one is always played.

I have also noticed that when changing the player in chromecast I need to kill the process so that it starts using libvlc correctly.

Audio config:
audio output - direct
Audio Bitstream DTS - enabled

`Input #0, matroska,webm, from 'Episode S01E03 - 1080p.mkv':
  Metadata:
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2022-06-02T19:03:49.000000Z
  Duration: 00:22:01.34, start: 0.000000, bitrate: 3921 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS-eng         : 2958533
      DURATION-eng    : 00:22:01.320000000
      NUMBER_OF_FRAMES-eng: 31680
      NUMBER_OF_BYTES-eng: 488646173
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:1(spa): Audio: eac3, 48000 Hz, 2 channels, fltp (default)
    Metadata:
      title           : Castellano DD+ 2.0 @ 224 kbps
      BPS-eng         : 224000
      DURATION-eng    : 00:22:01.344000000
      NUMBER_OF_FRAMES-eng: 41292
      NUMBER_OF_BYTES-eng: 36997632
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(spa): Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      title           : Castellano DD 2.0 @ 256 kbps
      BPS-eng         : 256000
      DURATION-eng    : 00:22:01.344000000
      NUMBER_OF_FRAMES-eng: 41292
      NUMBER_OF_BYTES-eng: 42283008
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:3(eng): Audio: eac3, 48000 Hz, 2 channels, fltp
    Metadata:
      title           : Inglés DD+ 2.0 @ 224 kbps
      BPS-eng         : 224000
      DURATION-eng    : 00:22:01.344000000
      NUMBER_OF_FRAMES-eng: 41292
      NUMBER_OF_BYTES-eng: 36997632
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:4(eng): Audio: ac3, 48000 Hz, stereo, fltp, 256 kb/s
    Metadata:
      title           : Inglés DD 2.0 @ 256 kbps
      BPS-eng         : 256000
      DURATION-eng    : 00:22:01.344000000
      NUMBER_OF_FRAMES-eng: 41292
      NUMBER_OF_BYTES-eng: 42283008
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:5(spa): Subtitle: subrip
    Metadata:
      title           : Castellano [Completos]
      BPS-eng         : 90
      DURATION-eng    : 00:21:32.933000000
      NUMBER_OF_FRAMES-eng: 393
      NUMBER_OF_BYTES-eng: 14622
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:6(eng): Subtitle: subrip
    Metadata:
      title           : Inglés [Para Sordos]
      BPS-eng         : 98
      DURATION-eng    : 00:21:27.053000000
      NUMBER_OF_FRAMES-eng: 468
      NUMBER_OF_BYTES-eng: 15818
      _STATISTICS_WRITING_APP-eng: mkvmerge v45.0.0 ('Heaven in Pennies') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-06-02 19:03:49
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
`
