### PR TITLE
Fix LiveTV Guide Issue #2144

### LINKED ISSUE #2144: Live TV guide time doesn't update
### Describe the bug

When you are watching a program, and go back to the Guide, the time is stuck on when you started watching the program, and not the current time.  For example, watching an NFL game that starts at 12pm, when the game is over you hit the back button and the guide is still at 12pm

### Logs

_No response_

### Application version

0.14.3

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Cube

### Android version

Fire OS 7.0.6.3

### Jellyfin server version

10.8.4

### PR DESCRIPTION
**Pull request by kylep09**
Fixed Live TV Guide.

**Changes**
The TV Guide currently does not adjust guide beginning time when returning to the guide from viewing. This PR fixes that problem so that every time the viewer returns to the guide, it fetches the current time and repopulates the guide using the new time. This fix also changes the time so that the guide beginning time text displays the current time that the guide was accessed.

**Issues**
Fixes #2144 

## Summary by CodeRabbit

* **Improvements**
  * Timeline in the Live TV guide now starts exactly at the current minute and dynamically adjusts label intervals and widths for more accurate alignment and spacing.
  * TV program data is now always refreshed when viewing the guide, ensuring up-to-date information is displayed.

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java [hunk 1]
```diff
@@ -707,18 +708,20 @@ private void fillTimeLine(LocalDateTime start, int hours) {
...
+
+        int interval = mCurrentGuideStart.getMinute() >= 30 ? 60 - mCurrentGuideStart.getMinute() : 30 - mCurrentGuideStart.getMinute();
         mTimeline.removeAllViews();
 
         LocalDateTime current = mCurrentGuideStart;
         while (current.isBefore(mCurrentGuideEnd)) {
             TextView time = new TextView(requireContext());
             time.setText(DateTimeExtensionsKt.getTimeFormatter(getContext()).format(current));
-            time.setWidth(interval == 30 ? halfHour : oneHour);
+            //time.setWidth(interval != 60 ? (interval * guideRowWidthPerMinPx) : oneHour);
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java]: No need to keep commented code

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
I'm unable to test these changes as I do not have Live TV setup right now. So I'm just going to assume it works, unless someone else is able to confirm that.

File: app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java (hunk 1 above)
Comment (kylep09) [reply app/src/main/java/org/jellyfin/androidtv/ui/livetv/LiveTvGuideFragment.java]: Commented line has been removed.

**Review by nielsvanvelzen — APPROVED** [review]

**Comment by nielsvanvelzen** [comment]
@coderabbitai review

**Comment by nielsvanvelzen** [comment]
Thanks for the PR!
