### PR TITLE
Refactor alpha picker in Kotlin and fix Fire OS compatability

### LINKED ISSUE #755: Search by letters does not work on Fire TV Stick 4K
**Describe the bug**
Search by letters does not work on Fire TV 4K the list of letters is displayed but there is no cursor that moves through them.
I also have a Fire TV Stick (3rd generation) and that one works correctly.

**Screenshots**

**System (please complete the following information):**
 - Fire TV 
 - Amazon
 - Device model: Fire TV Stick 4K
 - Jellyfin server version: 10.8.0

### PR DESCRIPTION
**Pull request by thornbill**
**Changes**
* Fixes focus issues on Fire OS in the alpha picker
* Rewrites alpha picker in Kotlin
* Updates popup styling

**Issues**
Fixes #755

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+	context: Context,
+	attrs: AttributeSet?
+) : LinearLayout(context, attrs) {
+	var onAlphaSelected: (s: String) -> Unit = {}
+
+	init {
+		removeAllViews()
+
+		val letters = "#${resources.getString(R.string.byletter_letters)}"
+		letters.toCharArray().forEach {
```
[the remark this answers is not in the document]
Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:19]: I'd suggest naming the parameter too, so 
```suggestion
		letters.forEach { letter ->
```
instead of `it`

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+import android.content.Context
+import android.util.AttributeSet
+import android.widget.Button
+import android.widget.LinearLayout
+import org.jellyfin.androidtv.R
+
+class AlphaPicker(
+	context: Context,
+	attrs: AttributeSet?
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:11]:
```suggestion
	attrs: AttributeSet? = null
```

Automatically creates a secondary constructor with a null value

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+			button.text = it.toString()
+			button.setOnClickListener { _ ->
+				this.onAlphaSelected(it.toString())
+			}
+
+			addView(button)
+		}
+	}
+
+	fun focus(text: String?) {
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:31]: Wouldn't it make more sense to accept a `Char` here?

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:31]: Also makes more sense for it to be not-null I guess

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+		if (!text.isNullOrBlank()) {
+			for (i in 1..childCount) {
+				val button = getChildAt(i) as Button
+				if (text == button.text) {
+					button.requestFocus()
+					return
+				}
+			}
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:39]: Something like:

```kotlin
children
  .filterIsInstance<Button>()
  .firstOrNull { it.text == text }
  ?.focus()
```

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt (hunk 3 above)
Comment (thornbill) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt]: Probably... I switched to only using Chars in the class and added null checks on the Java side.

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+	var onAlphaSelected: (letter: Char) -> Unit = {}
+
+	init {
+		removeAllViews()
+
+		val letters = "#${resources.getString(R.string.byletter_letters)}"
+		letters.forEach { letter ->
+			// NOTE: We must use a Button here and NOT AppCompatButton due to focus issues on Fire OS
+			val button = View.inflate(context, R.layout.alpha_picker_button, null) as Button
+			button.apply {
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:24]:
```suggestion
			val binding = AlphaPickerButtonBinding.inflate(LayoutInflater.from(context))
			binding.button.apply {
```
(add id="button" or some other id to the XML)

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+				text = letter.toString()
+				setOnClickListener { _ ->
+					onAlphaSelected(letter)
+				}
+			}
+
+			addView(button)
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:31]:
```suggestion
			addView(binding.root)
```

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+import org.jellyfin.androidtv.R
+
+class AlphaPicker(
+	context: Context,
+	attrs: AttributeSet? = null
+) : LinearLayout(context, attrs) {
+	var onAlphaSelected: (letter: Char) -> Unit = {}
+
+	init {
+		removeAllViews()
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:18]: I don't think this is needed because `init` is basically the constructor body so there shouldn't be any child views.

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt (hunk 5 above)
Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:24]: Actually use `val binding = AlphaPickerButtonBinding.inflate(LayoutInflater.from(context), this, false)` so it attaches to the parent to inherit styling (for themes)

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java [hunk 8]
```diff
@@ -496,48 +495,43 @@ public void onClick(View v) {
...
-        Activity mActivity;
-        JumpList mJumplist;
+        private final PopupWindow popupWindow;
+        private final AlphaPicker alphaPicker;
 
-        JumplistPopup(Activity activity) {
-            mActivity = activity;
-            LayoutInflater inflater = (LayoutInflater) activity.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
+        JumplistPopup() {
+            LayoutInflater inflater = (LayoutInflater) requireActivity().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:505]: `LayoutInflater.from(getContext())`

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java [hunk 9]
```diff
@@ -496,48 +495,43 @@ public void onClick(View v) {
...
             View layout = inflater.inflate(R.layout.empty_popup, null);
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:506]:
```suggestion
            View layout = inflater.inflate(R.layout.empty_popup, mGridDock, false);
```

I'm not exactly sure if mgriddock is the parent, but it's used in the `show` function

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java (hunk 8 above)
Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:505]: (or requireContext())

File: app/src/main/res/layout/empty_popup.xml [hunk 10]
```diff
@@ -2,6 +2,6 @@
 <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
     android:layout_width="match_parent"
     android:layout_height="match_parent"
-    android:background="@color/black_transparent"
+    android:background="?attr/popupWindowBackground"
```
Comment (nielsvanvelzen) [inline app/src/main/res/layout/empty_popup.xml:5]: This linter warning can be ignored (`tools:ignore="Overdraw"`)

File: app/src/main/res/layout/empty_popup.xml [hunk 11]
```diff
@@ -2,6 +2,6 @@
 <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
```
Comment (nielsvanvelzen) [inline app/src/main/res/layout/empty_popup.xml:2]: Rename this file to `popup_empty` please

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]
The longest value for the `byletter_letters` string is the russian translation:
`АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯABCDEFGHIJKLMNOPQRSTUVWXYZ`

It overflows the picker right now so half of the characters are not selectable. The parent view should be scrollable or allow wrapping.

**Comment by thornbill** [comment]
The other issues should be fixed, but I still need to address the overflowing for longer alphabets.

File: app/src/main/res/layout/alpha_picker_button.xml [hunk 12]
```diff
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="utf-8"?>
```
Comment (nielsvanvelzen) [inline app/src/main/res/layout/alpha_picker_button.xml:1]: File should be named `view_button_alpha_picker` because it's used in a (custom-) view class and is a button.

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 13]
```diff
@@ -0,0 +1,40 @@
...
+class AlphaPicker(
+	context: Context,
+	attrs: AttributeSet? = null
+) : LinearLayout(context, attrs) {
+	var onAlphaSelected: (letter: Char) -> Unit = {}
+
+	init {
+		val letters = "#${resources.getString(R.string.byletter_letters)}"
+		letters.forEach { letter ->
+			// NOTE: We must use a Button here and NOT AppCompatButton due to focus issues on Fire OS
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:21]: I don't this comment matters now :p

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java [hunk 14]
```diff
@@ -496,48 +493,43 @@ public void onClick(View v) {
...
-                }
+        private final int WIDTH = Utils.convertDpToPixel(requireContext(), 900);
+        private final int HEIGHT = Utils.convertDpToPixel(requireContext(), 55);
+
+        private final PopupWindow popupWindow;
+        private final AlphaPicker alphaPicker;
+
+        JumplistPopup() {
+            LayoutInflater inflater = LayoutInflater.from(requireContext());
+            View layout = inflater.inflate(R.layout.popup_empty, mGridDock, false);
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:504]: Ideally this should also use view binding (PopupEmptyBinding.inflate...) but not necessarily in the scope of this PR as it just modified the existing code.

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt (hunk 13 above)
Comment (thornbill) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:21]: Well it does, but maybe it should be moved to the XML file?

Comment (thornbill) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt]: Moved it to the XML file.

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java (hunk 14 above)
Comment (thornbill) [reply app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:504]: I would say it is out of scope personally. This file is a mess in general. :scream:

**Comment by thornbill** [comment]
Ok I have added horizontal scrolling now. I would prefer it if the buttons were centered when they don't overflow, but that seems a bit painful to implement unless I am just overlooking something obvious... :sweat_smile:

File: app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java [hunk 15]
```diff
@@ -514,10 +515,14 @@ public void onClick(View v) {
                 dismiss();
                 return null;
             });
-            alphaPicker.setGravity(Gravity.CENTER_HORIZONTAL);
+
+            HorizontalScrollView scrollView = new HorizontalScrollView(requireContext());
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/browsing/StdGridFragment.java:519]: I think it would make more sense to change the alphapicker to extend HorizontalScrollView, add the LinearLayout as a child and then add the buttons to the linearlayout.

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt [hunk 16]
```diff
@@ -0,0 +1,47 @@
...
+
+class AlphaPicker(
+	context: Context,
+	attrs: AttributeSet? = null
+) : HorizontalScrollView(context, attrs) {
+	var onAlphaSelected: (letter: Char) -> Unit = {}
+
+	init {
+		isFocusable = false
+		isFocusableInTouchMode = false
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:21]:
```suggestion
		isFocusableInTouchMode = false
		isHorizontalScrollBarEnabled = false
```

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt (hunk 16 above)
Comment (thornbill) [reply app/src/main/java/org/jellyfin/androidtv/ui/AlphaPicker.kt:21]: :+1: updated

**Review by nielsvanvelzen — APPROVED** [review]
