### PR TITLE
Improve BaseRowItem refreshing (fix crash after item deletion)

### LINKED ISSUE #2948: Error deleting item
### Describe the bug

Upon deleting item after playing there was a crash of the client, seems sporadic as some items delete without an issue.

Movie details taken out of log.

Server should be quick enough to handle as nothing else was happening on it and it's a Ryzen 7 5700x with 16GB of RAM.

### Logs
```
[2023-08-05 23:54:09.638 +01:00] [INF] [69] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: "Movie", Name: "", Path: "", Id: 7422d415-0862-46d1-003b-c51ec0e45603
[2023-08-05 23:54:09.641 +01:00] [INF] [69] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Movie", Name: "", Path: "", Id: 7422d415-0862-46d1-003b-c51ec0e45603
[2023-08-05 23:54:10.340 +01:00] [INF] [69] Emby.Server.Implementations.Library.LibraryManager: Deleting item path, Type: "Movie", Name: "", Path: "", Id: 7422d415-0862-46d1-003b-c51ec0e45603
[2023-08-05 23:54:10.358 +01:00] [WRN] [69] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.1.253:8096/Items/7422d415-0862-46d1-003b-c51ec0e45603" to "192.168.1.200" in 0:00:00.7309241 with Status Code 204
[2023-08-05 23:54:11.551 +01:00] [ERR] [106] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/8294109f-a0bc-4635-a8a1-453d41a2221f/Items/7422d415-0862-46d1-003b-c51ec0e45603".
System.NullReferenceException: Object reference not set to an instance of an object.
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDtoInternal(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Emby.Server.Implementations.Dto.DtoService.GetBaseItemDto(BaseItem item, DtoOptions options, User user, BaseItem owner)
   at Jellyfin.Api.Controllers.UserLibraryController.GetItem(Guid userId, Guid itemId)
   at lambda_method1234(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2023-08-05 23:54:16.129 +01:00] [WRN] [67] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.200" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2023-08-05 23:54:16.131 +01:00] [INF] [67] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.200" closed
[2023-08-05 23:55:10.332 +01:00] [INF] [72] Emby.Server.Implementations.IO.LibraryMonitor: "" ("") will be refreshed.
```
### Application version

v0.16.0-beta.2

### Where did you install the app from?

Google Play

### Device information

Sony Bravia TV KD-49XG9005

### Android version

Latest for that model - 9?

### Jellyfin server version

10.8.10

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
**Changes**

- Fix race conditions where selected item would change during refresh
- Catch API exceptions
- Remove item from adapter when refresh fails (~~should actually only happen with a 404 but the server returns a 500 🤷~~)
- Format some files

**Issues**

Fixes #2948

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt [hunk 1]
```diff
@@ -320,11 +333,16 @@ open class BaseRowItem protected constructor(
 			}
 
 			scope.launch(Dispatchers.IO) {
-				val response by api.userLibraryApi.getItem(itemId = id.toUUID())
-				baseItem = response
+				baseItem = try {
+					api.userLibraryApi.getItem(itemId = id.toUUID()).content
+				} catch (err: ApiClientException) {
+					Timber.e(err, "Failed to refresh item")
+					// TODO Only set tot null when returned status is 404
```
Comment (crobibero) [inline app/src/main/java/org/jellyfin/androidtv/ui/itemhandling/BaseRowItem.kt:340]:
```suggestion
					// TODO Only set to null when returned status is 404
```

**Review by crobibero — APPROVED** [review]
