### PR TITLE
handle exoplayer track selection indexes starting at 1

### LINKED ISSUE #619: Media is constantly played using the wrong sound track
**Describe the bug**
I wanted to view a movie which has 2 sound tracks (french and english) in french and whatever track I select in the android tv UI the movie plays in english.
When I play the same movie from my browser the movie is played in french.

**To Reproduce**

Not sure I have a 100% reproducble procedure.

**Expected behavior**
Be able to play the sound track I want.

**Logs**
I did not spot any particular error related to this problem on the server 

**Screenshots**

some media information (sorry In french)
image

Audio info
```
    Stream #0:1(fre): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      title           : VFF DTS @754kbps
      BPS             : 768000
      BPS-eng         : 768000
      DURATION        : 02:05:55.584000000
      DURATION-eng    : 02:05:55.584000000
      NUMBER_OF_FRAMES: 708336
      NUMBER_OF_FRAMES-eng: 708336
      NUMBER_OF_BYTES : 725336064
      NUMBER_OF_BYTES-eng: 725336064
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-28 17:40:44
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-28 17:40:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : VOA AAC 2.0 @128kb
      BPS             : 127913
      BPS-eng         : 127913
      DURATION        : 02:05:55.605000000
      DURATION-eng    : 02:05:55.605000000
      NUMBER_OF_FRAMES: 354169
      NUMBER_OF_FRAMES-eng: 354169
      NUMBER_OF_BYTES : 120808057
      NUMBER_OF_BYTES-eng: 120808057
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-28 17:40:44
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-28 17:40:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**System (please complete the following information):**
 - Android TV or Fire TV version: Android but don't know the type, it's installed on my set top box provided by my ISP
 - Device manufacturer: Free (free.fr French ISP)
 - Device model: freebox Pop
 - Jellyfin server version: 10.6.4
 - Jellyfin server version: 0.11.4

**Additional context**

If you need some logs that may contain info please ask.

### PR DESCRIPTION
**Pull request by mueslimak3r**
**Changes**
* `offsetStreamIndex()` can now account for a players indexing from 1 (exoplayer starts at 1, libVLC starts at 0)
* return `true` when trying to set a track with exoplayer and it is already selected. Returning false indicates an error/that transcoding may be needed so the stream is recreated, and that is not needed in this situation.

**Issues**
* fixes #619 
* exoplayer track indexes start at 1 but somewhere in the several refactors accounting for this was left out.
 mentioned here:
 https://github.com/jellyfin/jellyfin-androidtv/pull/1732#issuecomment-1159758029

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java [hunk 1]
```diff
@@ -432,15 +432,23 @@ public void disableSubs() {
         }
     }
 
-    private int offsetStreamIndex(int index, boolean adjustByAdding, @Nullable List<MediaStream> allStreams) {
+    private int offsetStreamIndex(int index, boolean adjustByAdding, boolean IndexStartsAtOne, @Nullable List<MediaStream> allStreams) {
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java:435]:
```suggestion
    private int offsetStreamIndex(int index, boolean adjustByAdding, boolean indexStartsAtOne, @Nullable List<MediaStream> allStreams) {
```

**Review by nielsvanvelzen — CHANGES_REQUESTED** [review]

**Review by nielsvanvelzen — APPROVED** [review]
