### PR TITLE
Check if content provider is available in LeanbackChannelWorker

### LINKED ISSUE #1015: Client for Android TV crash after connect to server
**Describe the bug**
Client for Android TV crash after connect to server

**To Reproduce**
1. Open Jellyfin
2. Select user (no pswrd)
3. Crash

**Logs**
Adb log

> 
> 2956  3005 E BufferQueueProducer: [org.jellyfin.androidtv.debug/org.jellyfin.androidtv.startup.StartupActivity#0] disconnect: not connected (req=1)
> 7585  7643 E ActivityThread: Failed to find provider info for android.media.tv
> 7585  7643 E ACRA    : ACRA caught a IllegalArgumentException for org.jellyfin.androidtv.debug
> 7585  7643 E ACRA    : java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/watch_next_program
> 7585  7643 E ACRA    :      at android.content.ContentResolver.delete(ContentResolver.java:1680)
> 7585  7643 E ACRA    :      at org.jellyfin.androidtv.channels.ChannelManager$updateWatchNext$2.invokeSuspend(ChannelManager.kt:61)
> 7585  7643 E ACRA    :      at org.jellyfin.androidtv.channels.ChannelManager$updateWatchNext$2.invoke(Unknown Source:10)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
> 7585  7643 E ACRA    :      at org.jellyfin.androidtv.channels.ChannelManager.updateWatchNext(ChannelManager.kt:59)
> 7585  7643 E ACRA    :      at org.jellyfin.androidtv.channels.ChannelManager$update$1.invokeSuspend(ChannelManager.kt:51)
> 7585  7643 E ACRA    :      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
> 7585  7643 E ACRA    :      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
> 2832  2832 E SELinux : avc:  denied  { find } for service=meminfo pid=7658 uid=10032 scontext=u:r:untrusted_app:s0:c32,c256,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
> 3182  3357 E InputDispatcher: channel 'a932a8e org.jellyfin.androidtv.debug/org.jellyfin.androidtv.browsing.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 3182  3357 E InputDispatcher: channel '6751060 org.jellyfin.androidtv.debug/org.jellyfin.androidtv.startup.SelectUserActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

Server log

> [2021-07-12 19:21:52.760 +00:00] [INF] [77] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.5" request
> [2021-07-12 19:21:57.087 +00:00] [INF] [60] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "play" has succeeded.
> [2021-07-12 19:21:57.088 +00:00] [INF] [60] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "play": 2/0
> [2021-07-12 19:21:57.090 +00:00] [INF] [60] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "9__________e"
> [2021-07-12 19:21:58.245 +00:00] [WRN] [74] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.5" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
> [2021-07-12 19:21:58.260 +00:00] [INF] [74] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.5" closed

**System (please complete the following information):**
- Server 10.08 (linuxserver docker)
- Client 0.11.5
- Device Android TV box

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
Huawei was inspired by Samsung and wanted to break everything too. They decided that on HarmonyOS TV all apps get a false-positive for the leanback system feature so that all apps crash as soon as they try to integrate with it.

Fortunately this issue wouldn't crash the app starting from 0.12 because leanback integration was moved to a background worker, which uses a separate thread.

**Changes**

- Added an additional check to see if the content provider (android.media.tv) is available on the system

**Issues**

Fixes #1015

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt [hunk 1]
```diff
@@ -60,6 +60,7 @@ class LeanbackChannelWorker(
 	 */
 	private val isSupported = Build.VERSION.SDK_INT >= Build.VERSION_CODES.O
 		&& context.packageManager.hasSystemFeature("android.software.leanback")
+		&& context.packageManager.resolveContentProvider(TvContractCompat.AUTHORITY, 0) != null
```
Comment (thornbill) [inline app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt:63]: Perhaps it would be good to add a comment here as to why this check is necessary.

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt:65]: Fixed all other comments too (added punctuation and remove line breaks).

**Review by thornbill — APPROVED** [review]
