### PR TITLE
Check if fragment is null in PlaybackController.play

### LINKED ISSUE #3471: Crash when opening newer Library Items (TV Show/Movie)
### Describe the bug

If I click on some newer added TV Shows or Movies, my Jellyfin Android App is crashing. If I press play from the dashboard, it works. It also works for older items.
The logs are not transfered to the server. It crashed so often today and I have only one logfile so far.
I tried to upgrade the app to the latest version (0.16.7) but manual install from the apk does not work for me. Latest version is not yet available in Amazon Store.

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.6
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***:
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getContext()' on a null object reference
        at org.jellyfin.androidtv.ui.playback.PlaybackController.buildVLCOptions(PlaybackController.java:591)
        at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:540)
        at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:435)
        at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.play(VideoPlayerAdapter.java:29)
        at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:12)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:292)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.setOnActionClickedListener$lambda$0(CustomPlaybackFragmentGlueHost.kt:21)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.$r8$lambda$GOPxzWh-j6mlduoWRi-elcZerjA(Unknown Source:0)
        at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost$$ExternalSyntheticLambda0.onItemClicked(Unknown Source:2)
        at androidx.leanback.app.PlaybackSupportFragment$1.onItemClicked(PlaybackSupportFragment.java:175)
        at androidx.leanback.widget.PlaybackTransportRowPresenter$2.onControlClicked(PlaybackTransportRowPresenter.java:575)
        at androidx.leanback.widget.ControlBarPresenter$ViewHolder$3.onClick(ControlBarPresenter.java:164)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.onKeyUp(View.java:13216)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2832)
        at android.view.View.dispatchKeyEvent(View.java:12450)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:438)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1821)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3391)
        at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
        at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:208)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5057)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4923)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4636)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4797)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:178)
        at android.app.ActivityThread.main(ActivityThread.java:6775)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
***Logcat***:
```log
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4636)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4797)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.os.MessageQueue.nativePollOnce(Native Method)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.os.MessageQueue.next(MessageQueue.java:326)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.os.Looper.loop(Looper.java:178)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at android.app.ActivityThread.main(ActivityThread.java:6775)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at java.lang.reflect.Method.invoke(Native Method)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-26 14:06:13.479 E/AndroidRuntime( 9410):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
03-26 14:06:13.480 E/ACRA    ( 9410): ACRA caught a NullPointerException for org.jellyfin.androidtv
03-26 14:06:13.480 E/ACRA    ( 9410): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.jellyfin.androidtv.ui.playback.CustomPlaybackOverlayFragment.getContext()' on a null object reference
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.PlaybackController.buildVLCOptions(PlaybackController.java:591)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:540)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.PlaybackController.play(PlaybackController.java:435)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.VideoPlayerAdapter.play(VideoPlayerAdapter.java:29)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.action.PlayPauseAction.onActionClicked(PlayPauseAction.kt:12)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackTransportControlGlue.onActionClicked(CustomPlaybackTransportControlGlue.java:292)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.setOnActionClickedListener$lambda$0(CustomPlaybackFragmentGlueHost.kt:21)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost.$r8$lambda$GOPxzWh-j6mlduoWRi-elcZerjA(Unknown Source:0)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.playback.overlay.CustomPlaybackFragmentGlueHost$$ExternalSyntheticLambda0.onItemClicked(Unknown Source:2)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.leanback.app.PlaybackSupportFragment$1.onItemClicked(PlaybackSupportFragment.java:175)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.leanback.widget.PlaybackTransportRowPresenter$2.onControlClicked(PlaybackTransportRowPresenter.java:575)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.leanback.widget.ControlBarPresenter$ViewHolder$3.onClick(ControlBarPresenter.java:164)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.View.performClick(View.java:6597)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.View.performClickInternal(View.java:6574)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.View.onKeyUp(View.java:13216)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.KeyEvent.dispatch(KeyEvent.java:2832)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.View.dispatchKeyEvent(View.java:12450)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.leanback.widget.PlaybackTransportRowView.dispatchKeyEvent(PlaybackTransportRowView.java:71)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.leanback.widget.BaseGridView.dispatchKeyEvent(BaseGridView.java:1081)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1896)
03-26 14:06:13.480 E/ACRA    ( 9410):   at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:438)
03-26 14:06:13.480 E/ACRA    ( 9410):   at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1821)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.app.Activity.dispatchKeyEvent(Activity.java:3391)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
03-26 14:06:13.480 E/ACRA    ( 9410):   at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
03-26 14:06:13.480 E/ACRA    ( 9410):   at org.jellyfin.androidtv.ui.browsing.MainActivity.dispatchKeyEvent(MainActivity.kt:208)
03-26 14:06:13.480 E/ACRA    ( 9410):   at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:352)
03-26 14:06:13.480 E/ACRA    ( 9410):   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5057)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4923)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4471)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4444)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4497)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4463)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4636)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4797)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2571)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2081)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2072)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2548)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.os.MessageQueue.nativePollOnce(Native Method)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.os.MessageQueue.next(MessageQueue.java:326)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.os.Looper.loop(Looper.java:178)
03-26 14:06:13.481 E/ACRA    ( 9410):   at android.app.ActivityThread.main(ActivityThread.java:6775)
03-26 14:06:13.481 E/ACRA    ( 9410):   at java.lang.reflect.Method.invoke(Native Method)
03-26 14:06:13.481 E/ACRA    ( 9410):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
03-26 14:06:13.481 E/ACRA    ( 9410):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

### App information

***App version***: `0.16.6` (`160699`)
***Package name***: `org.jellyfin.androidtv`
***Build***:
```json
{"BOARD":"kara","BOOTLOADER":"unknown","BRAND":"Amazon","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"kara","DISPLAY":"PS7669.4007N","FINGERPRINT":"Amazon\/kara\/kara:9\/PS7669.4007N\/0029696698112:user\/amz-p,release-keys","HARDWARE":"mt8696","HOST":"i3-ri-14-use1a-b-16-04-fos-stk2-4","ID":"PS7669.4007N","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Amazon","MODEL":"AFTKA","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"kara","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"amz-p,release-keys","TIME":1706694874000,"TYPE":"user","UNKNOWN":"unknown","USER":"build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"PPR1.180610.009","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"0029696698244","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2023-12-01"}}
```
***Build config***:
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160699,"VERSION_NAME":"0.16.6"}
```

### Device information

***Android version***: `9`
***Device brand***: `Amazon`
***Device product***: `kara`
***Device model***: `AFTKA`

### Crash information

***Start time***: `2024-03-26T09:27:04.039+01:00`
***Crash time***: `2024-03-26T14:06:13.541+01:00`

### Application version

0.16.6

### Where did you install the app from?

Amazon Appstore

### Device information

FireTV Stick 4K Max

### Android version

FireOS 7.6.6.9

### Jellyfin server version

10.8.13

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
We already had a lot of null checks in this function but some branches still tried to use mFragment causing a NPE. Refactored the function to check for null once in the top and return if is it null.

**Changes**

Check if fragment is null in PlaybackController.play and noop if it is.

**Issues**

Fixes #3471

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java [hunk 1]
```diff
@@ -442,6 +442,11 @@ private void play(long position, @Nullable Integer forcedSubtitleIndex) {
             position = 0;
         }
 
+        if (mFragment == null) {
+            Timber.i("mFragment is null, returning");
```
Comment (thornbill) [inline app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java:446]: Maybe this should be a warning?

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java]: Good call, I've also updated the earlier log statement from debug to info as it is quite useful.

**Review by thornbill — APPROVED** [review]
