### PR TITLE
use ts for exoplayer transcodes

### LINKED ISSUE #1410: 0.13beta1 track transcoding bug
### Describe the bug

1.Select exoPlayer to play
2.Audio selection pass through
Then, On devices that support AC3 and DTS, track transcoding is AAC and silent.
If mixed stereo is selected, the track is transcoded to AAC and works is OK.
The old version will be transcoded to AC3 according to the option, and it works well.
We hope to add the option of forced AC3 / DTS transcoding to make more devices work.This is very important.Android devices are difficult to set up multi-channel, and the transcoding of the old version of AC3 / DTS is a miracle.
Thanks.

### Logs

_No response_

### Application version

0.13 beta1

### Where did you install the app from?

_No response_

### Device information

android TV

### Android version

Android 7,Android 9

### Jellyfin server version

10.8.0 alpha5

### PR DESCRIPTION
**Pull request by mueslimak3r**
**Changes**
* remove the code that prevents seeking when the container is TS
* replaced MP4 with TS (still uses HLS) in `ExoplayerProfile`
* modify the TS search bytes to match what jellyfin-android does:
  https://github.com/jellyfin/jellyfin-android/blob/6d42621e16bc38d805cf2861a6a10f65ca2d626c/app/src/main/java/org/jellyfin/mobile/app/AppModule.kt#L77
* update `addAc3Streaming` so it can enable AC3 for more than one container (mkv, ts)

**Issues**
* fixes #1410

### CODE REVIEW

File: app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt [hunk 1]
```diff
@@ -143,12 +143,16 @@ object ProfileHelper {
...
+		val containers = arrayOf(ContainerTypes.MKV, ContainerTypes.TS)
+		containers.forEach { c ->
+			Timber.d("trying to match transcoding profile for %s", c)
+			val transcodingProfile = findTranscodingProfile(profile, c) ?: return@forEach
+
+			Timber.i("*** Adding AC3 as supported transcoded audio for %s", c)
+			transcodingProfile.audioCodec = when (primary) {
+				true -> "${CodecTypes.AC3},${transcodingProfile.audioCodec}"
+				false -> "${transcodingProfile.audioCodec},${CodecTypes.AC3}"
+			}
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt:155]: Looking at the usages of `addAc3Streaming` the primary argument is always true so this function can be simplified a bit.

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt:155]: In fact, it's only used for exoplayer profiles so we might just pass a boolean to the exoplayerprofile constructor whether to enable or disable ac3 and remove this helper function.

https://github.com/jellyfin/jellyfin-androidtv/blob/8424e581583743d7d0a09902716defbfde875bc7/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java#L498-L502

Comment (mueslimak3r) [reply app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt:155]: `UserPreferences.Companion.getAc3Enabled()` looks like it just resolves to !DeviceUtils.isFireTvStickGen1()
https://cs.github.com/jellyfin/jellyfin-androidtv?q=pref_bitstream_ac3

So anything using exoplayer profile will qualify, and ac3 might as well just be added to the profile by default?

Comment (nielsvanvelzen) [reply app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt:155]: The preference can still be set in the app. It's disabled by default on fire tv.

File: app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt [hunk 2]
```diff
@@ -139,23 +139,6 @@ object ProfileHelper {
...
-
-			Timber.i("*** Adding AC3 as supported transcoded audio for %s", c)
-			transcodingProfile.audioCodec = when (primary) {
-				true -> "${CodecTypes.AC3},${transcodingProfile.audioCodec}"
-				false -> "${transcodingProfile.audioCodec},${CodecTypes.AC3}"
-			}
-		}
-	}
-
 	private fun findTranscodingProfile(
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/util/profile/ProfileHelper.kt:142]: This one is unused now and can be removed

**Review by nielsvanvelzen — APPROVED** [review]
