### PR TITLE
Fix Hardcoded Texts

### LINKED ISSUE #507: hardcoded texts
**Describe the bug**
There is a few hardcoded text for dialogues in code. Please create keys for translations.
Here are the one I found within "setmessage". Maybe you find some others in usages of "Utils.showToast" or "Toast.makeText"

- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java#L97
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java#L132
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/Utils.java#L210-L211
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java#L660-L661
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java#L678-L679
~~https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java#L795~~
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java#L282
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java#L301
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java#L336
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java#L371-L372

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by PalAditya**
**Changes**

- Made changes to all static strings and replaced them with resource strings from strings.xml
- Did not make changes to FullDetailsActivity.java as per the comment in the issue
- Had a local build error (linting) on the string resource *lbl_unknown_key*, but it is unrelated to this PR

**Issues**

Fixes #507

### CODE REVIEW

**Comment by PalAditya** [comment]
I believe the codacy failing check can't be avoided and is not a fault of this PR 🤔

File: app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java [hunk 1]
```diff
@@ -675,13 +675,13 @@ public void onClick(DialogInterface dialog, int which) {
                         } else {
                             new AlertDialog.Builder(mActivity)
                                     .setTitle(R.string.lbl_delete)
-                                    .setMessage("This will PERMANENTLY DELETE " + mBaseItem.getName() + " from your library.  Are you VERY sure?")
-                                    .setPositiveButton("Delete", new DialogInterface.OnClickListener() {
+                                    .setMessage(R.string.warning_0 + mBaseItem.getName() + R.string.warning_1)
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java:678]: Using a string template is preferred for strings that contain dynamic elements. An example in this case: `This will PERMANENTLY DELETE %1$s from your library.  Are you VERY sure?`. The value can then be passed to the `getString` function as argument.

[Android documentation](https://developer.android.com/guide/topics/resources/string-resource.html#FormattingAndStyling)

File: app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java [hunk 2]
```diff
@@ -675,13 +675,13 @@ public void onClick(DialogInterface dialog, int which) {
...
+                                    .setPositiveButton(R.string.lbl_delete, new DialogInterface.OnClickListener() {
                                         public void onClick(DialogInterface dialog, int whichButton) {
                                             TvApp.getApplication().getApiClient().DeleteItem(mBaseItem.getId(), new EmptyResponse() {
                                                 @Override
                                                 public void onResponse() {
-                                                    Utils.showToast(mActivity, mBaseItem.getName() + " Deleted");
+                                                    Utils.showToast(mActivity, mBaseItem.getName() + R.string.lbl_deleted);
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java:684]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java [hunk 3]
```diff
@@ -368,8 +368,8 @@ public void onClick(DialogInterface dialog, int which) {
 
     private void requestGuidePage(final long startTime) {
         new AlertDialog.Builder(mActivity)
-                .setTitle("Load Guide Data")
-                .setMessage("Load " + (startTime > mCurrentLocalGuideStart ? "next " : "previous ") +getGuideHours()+" hours?")
+                .setTitle(R.string.lbl_load_guide_data)
+                .setMessage(R.string.lbl_load + (startTime > mCurrentLocalGuideStart ? R.string.lbl_next : R.string.lbl_previous) + getGuideHours() + R.string.lbl_hours_2)
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java:372]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java [hunk 4]
```diff
@@ -347,7 +347,7 @@ public void onClick(DialogInterface dialog, int which) {
                         TvApp.getApplication().getApiClient().CreatePlaylist(request, new Response<PlaylistCreationResult>() {
                             @Override
                             public void onResponse(PlaylistCreationResult response) {
-                                Toast.makeText(activity, "Queue saved as new playlist: "+text, Toast.LENGTH_LONG).show();
+                                Toast.makeText(activity, activity.getString(R.string.msg_queue_saved) + text, Toast.LENGTH_LONG).show();
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java:350]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java [hunk 5]
```diff
@@ -407,7 +407,7 @@ public static int addToVideoQueue(BaseItemDto item) {
             total += video.getRunTimeTicks() / 10000;
         }
 
-        Utils.showToast(TvApp.getApplication(), item.getName() + " added to video queue. Ends: "+android.text.format.DateFormat.getTimeFormat(TvApp.getApplication()).format(new Date(total)));
+        Utils.showToast(TvApp.getApplication(), item.getName() + TvApp.getApplication().getString(R.string.msg_added_to_video) +android.text.format.DateFormat.getTimeFormat(TvApp.getApplication()).format(new Date(total)));
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java:410]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java [hunk 6]
```diff
@@ -596,7 +596,7 @@ public void onResponse(StreamInfo response) {
 
             @Override
             public void onError(Exception exception) {
-                Utils.showToast(TvApp.getApplication(), "Unable to play audio " + exception.getLocalizedMessage());
+                Utils.showToast(TvApp.getApplication(), TvApp.getApplication().getString(R.string.audio_error) + exception.getLocalizedMessage());
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java:599]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/startup/DpadPwActivity.java [hunk 7]
```diff
@@ -92,10 +92,10 @@ public boolean onKeyUp(int keyCode, KeyEvent event) {
                     final Activity activity = this;
                     password.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD);
                     new AlertDialog.Builder(this)
-                            .setTitle("Enter Password")
-                            .setMessage("Please enter password for " + user.getName())
+                            .setTitle(R.string.password_prompt)
+                            .setMessage(R.string.password_prompt_message + user.getName())
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/startup/DpadPwActivity.java:96]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/util/Utils.java [hunk 8]
```diff
@@ -209,10 +209,10 @@ public static void processPasswordEntry(final Activity activity, final UserDto u
             final EditText password = new EditText(activity);
             password.setInputType(InputType.TYPE_CLASS_TEXT | InputType.TYPE_TEXT_VARIATION_PASSWORD);
             new AlertDialog.Builder(activity)
-                    .setTitle("Enter Password")
-                    .setMessage("Please enter password for " + user.getName())
+                    .setTitle(R.string.password_prompt)
+                    .setMessage(R.string.password_prompt_message + user.getName())
```
Comment (nielsvanvelzen) [inline app/src/main/java/org/jellyfin/androidtv/util/Utils.java:213]: Needs a string template

File: app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java (hunk 1 above)
Comment (PalAditya) [reply app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java]: Thanks for the documentation and clear guide. I believe I have resolved the issues, so kindly have a look

**Comment by nielsvanvelzen** [comment]
Looks good! I also found marked the `lbl_unknown_key` string for the chinese translation as "needs editing" in our translation platform because it was translated wrongly causing the errors to pop up.

**Review by nielsvanvelzen — APPROVED** [review]
